//! `Cargo.lock` — `version = N` + `[[package]]` TOML tables with
//! `name`/`version`/`source`/`checksum`/`dependencies`.

use core::str::from_utf8;

#[derive(Debug, Clone)]
/// Parsed census of `Cargo.lock`.
pub struct Cargolock {
    /// Top-level `version = N` lockfile schema.
    pub lockfile_version: usize,
    /// `[[package]]` entries.
    pub packages: usize,
    /// `name =` fields.
    pub names: usize,
    /// `version =` fields (packages + lockfile schema).
    pub versions: usize,
    /// `source =` fields.
    pub sources: usize,
    /// `source = "registry+…"` entries.
    pub registry: usize,
    /// `source = "git+…"` entries.
    pub git_sources: usize,
    /// `checksum =` hashes.
    pub checksums: usize,
    /// `dependencies = [` tables/arrays.
    pub dependency_blocks: usize,
    /// Dependency name strings inside `dependencies` arrays.
    pub dependencies: usize,
    /// `[[patch.unused]]`/`[[replace]]` tables.
    pub patches: usize,
    /// `[[metadata]]`/`[metadata]` tables.
    pub metadata: usize,
    /// Workspace `root`/`members` markers.
    pub workspace: usize,
    /// `#` comments.
    pub comments: usize,
}

/// `true` when the text looks like Cargo.lock.
#[must_use]
pub fn detect(b: &[u8]) -> bool {
    let Ok(t) = from_utf8(b) else {
        return false;
    };
    t.contains("[[package]]")
        && (t.contains("checksum") || t.contains("registry+") || t.contains("@generated by Cargo"))
}

fn in_deps(t: &str) -> usize {
    let mut n = 0;
    let mut inside = false;
    for l in t.lines() {
        let tr = l.trim();
        if let Some(after) = tr.strip_prefix("dependencies = [") {
            inside = true;
            // entries on the same line
            n += after.matches('"').count() / 2;
            if tr.contains(']') {
                inside = false;
            }
            continue;
        }
        if inside {
            if tr.starts_with(']') {
                inside = false;
            } else {
                n += tr.matches('"').count() / 2;
            }
        }
    }
    n
}

impl Cargolock {
    #[must_use]
    /// Parses `b` into `Cargolock`.
    pub fn parse(b: &[u8]) -> Option<Self> {
        let t = from_utf8(b).ok()?;
        if !detect(b) {
            return None;
        }
        Some(Self {
            lockfile_version: t
                .lines()
                .find_map(|l| l.trim().strip_prefix("version = "))
                .and_then(|v| v.trim_matches('"').parse().ok())
                .unwrap_or(0),
            packages: t.matches("[[package]]").count(),
            names: t.matches("name = ").count(),
            versions: t.matches("version = ").count(),
            sources: t.matches("source = ").count(),
            registry: t.matches("source = \"registry+").count(),
            git_sources: t.matches("source = \"git+").count(),
            checksums: t.matches("checksum = ").count(),
            dependency_blocks: t.matches("dependencies = [").count(),
            dependencies: in_deps(t),
            patches: t.matches("[[patch.unused]]").count() + t.matches("[[replace]]").count(),
            metadata: t.matches("[[metadata]]").count() + t.matches("[metadata]").count(),
            workspace: t.matches("[workspace]").count(),
            comments: t
                .lines()
                .filter(|l| l.trim_start().starts_with('#'))
                .count(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIX: &[u8] = b"# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"app\"\nversion = \"0\x2e1\x2e0\"\ndependencies = [\n \"serde\",\n \"toml\",\n]\n\n[[package]]\nname = \"serde\"\nversion = \"1\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"abc\"\n";

    #[test]
    fn detects_cargolock() {
        assert!(detect(FIX));
        assert!(!detect(b"[package]"));
    }

    #[test]
    fn parses_cargolock() {
        let c = Cargolock::parse(FIX).unwrap();
        assert_eq!(c.lockfile_version, 4);
        assert_eq!(c.packages, 2);
        assert_eq!(c.names, 2);
        assert_eq!(c.sources, 1);
        assert_eq!(c.registry, 1);
        assert_eq!(c.checksums, 1);
        assert_eq!(c.dependencies, 2);
        assert_eq!(c.comments, 1);
        assert!(Cargolock::parse(b"").is_none());
    }
}
