//! Farey sequences and the related lattice-sum machinery —
//! the order-`n` Farey sequence `F_n` (all reduced
//! fractions in `[0,1]` with denominator ≤ `n`), the
//! Stern–Brocot walk locating a target between Farey
//! neighbors, and `floor_sum`, the classic
//! `Σᵢ⌊(a·i + b)/m⌋` lattice-point count.
//!
//! `F_n` is generated by the *next-term* recurrence: from
//! consecutive terms `a/b < c/d`, the next is
//! `k·c − a / k·d − b` with `k = ⌊(n + b)/d⌋` — one
//! arithmetic step per term, no gcd calls.
//!
//! ```
//! use izanagi_kit::farey::{farey, floor_sum, neighbor};
//! use izanagi_kit::frac::Frac;
//! // F5 = 0/1, 1/5, 1/4, 1/3, 2/5, 1/2, 3/5, 2/3, 3/4, 4/5, 1/1
//! let f = farey(5);
//! assert_eq!(f.len(), 11);
//! assert_eq!(f[1], Frac::new(1, 5));
//! // Σᵢ₌₀..₄ ⌊(3i+1)/5⌋ = 0+0+1+2 = 3
//! assert_eq!(floor_sum(4, 5, 3, 1), 3);
//! // the Farey neighbors of 2/5 in F5
//! assert_eq!(neighbor(&Frac::new(2, 5), 5), (Frac::new(1, 3), Frac::new(1, 2)));
//! ```
//!
//! References: Hardy & Wright §III (the next-term
//! recurrence is their Theorem 29); `floor_sum` is the
//! AtCoder Library primitive (acl::math::floor_sum),
//! transcribed to `u128` arithmetic.

use crate::frac::Frac;

/// The order-`n` Farey sequence `[0/1, …, 1/1]` — `None`
/// for `n = 0`.
pub fn farey(n: u32) -> Vec<Frac> {
    if n == 0 {
        return Vec::new();
    }
    let mut out = vec![Frac::new(0, 1), Frac::new(1, i128::from(n))];
    loop {
        let a = out[out.len() - 2];
        let c = out[out.len() - 1];
        if c.num == 1 && c.den == 1 {
            // F_n terminates at 1/1 — required for n = 1
            // where the second seed term is already last
            break;
        }
        // next term e/f = (k·c − a)/(k·d − b) with
        // k = ⌊(n + b)/d⌋, where a/b < c/d are the last two
        let k = (i128::from(n) + a.den) / c.den;
        let nn = k * c.num - a.num;
        let nd = k * c.den - a.den;
        out.push(Frac::new(nn, nd));
    }
    out
}

/// `Σᵢ₌₀ⁿ⁻¹ ⌊(a·i + b)/m⌋` — the AtCoder `floor_sum`
/// primitive (exact lattice-point count under a line).
/// `0` when `m = 0` or `n = 0`. The Euclidean-recurrence
/// loop keeps intermediates in `u128` so `a·n + b` never
/// overflows.
pub fn floor_sum(n: u64, m: u64, mut a: u64, mut b: u64) -> u128 {
    if m == 0 {
        return 0;
    }
    let mut m = m;
    let mut n = n;
    let mut sum = 0u128;
    while n > 0 {
        if a >= m {
            sum += u128::from(n) * u128::from(n - 1) * u128::from(a / m) / 2;
            a %= m;
        }
        if b >= m {
            sum += u128::from(n) * u128::from(b / m);
            b %= m;
        }
        let ymax = u128::from(a) * u128::from(n) + u128::from(b);
        if ymax < u128::from(m) {
            break;
        }
        // n' = ymax/m < n since a,b < m — the recurrence
        // is the Euclidean algorithm on (a, m)
        n = (ymax / u128::from(m)) as u64;
        b = (ymax % u128::from(m)) as u64;
        std::mem::swap(&mut a, &mut m);
    }
    sum
}

/// The Farey fractions immediately adjacent to `f` in
/// `F_n` — `(predecessor, successor)` where `f` must be a
/// member (reduced, denominator ≤ `n`, in `[0,1]`). At the
/// endpoints the missing side is `f` itself; `(f, f)` when
/// `f` is not in `F_n` at all.
pub fn neighbor(f: &Frac, n: u32) -> (Frac, Frac) {
    let seq = farey(n);
    for (i, t) in seq.iter().enumerate() {
        if t == f {
            let prev = if i == 0 { *f } else { seq[i - 1] };
            let next = if i + 1 == seq.len() { *f } else { seq[i + 1] };
            return (prev, next);
        }
    }
    (*f, *f)
}

/// Stern–Brocot search path to `f` — the sequence of
/// `'L'`/`'R'` mediants from `0/1`/`1/1` that lands on `f`
/// (input must be a reduced fraction in the *open* `(0,1)`;
/// the endpoints `0/1`/`1/1` are never mediants, so `None`
/// otherwise). The path is the semiconvergent structure of
/// the target.
pub fn stern_brocot(f: &Frac) -> Option<Vec<u8>> {
    if f.num <= 0 || f.den <= 0 || f.num >= f.den {
        return None;
    }
    let (mut lo, mut hi) = (Frac::new(0, 1), Frac::new(1, 1));
    let mut path = Vec::new();
    for _ in 0..10_000 {
        let mid = Frac::new(lo.num + hi.num, lo.den + hi.den);
        if mid == *f {
            return Some(path);
        }
        if f.cmp_frac(&mid) == std::cmp::Ordering::Less {
            hi = mid;
            path.push(b'L');
        } else {
            lo = mid;
            path.push(b'R');
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rng::SplitMix64;

    #[test]
    fn basics() {
        let f5 = farey(5);
        assert_eq!(f5.len(), 11);
        assert_eq!(f5[0], Frac::new(0, 1));
        assert_eq!(f5[1], Frac::new(1, 5));
        assert_eq!(f5[5], Frac::new(1, 2));
        assert_eq!(f5[10], Frac::new(1, 1));
        assert_eq!(floor_sum(4, 5, 3, 1), 3);
        assert_eq!(floor_sum(0, 5, 3, 1), 0);
        // every term (i+10)/10 floors to 1 -> 10
        assert_eq!(floor_sum(10, 10, 1, 10), 10);
        let (lo, hi) = neighbor(&Frac::new(2, 5), 5);
        assert_eq!((lo, hi), (Frac::new(1, 3), Frac::new(1, 2)));
        assert_eq!(stern_brocot(&Frac::new(2, 5)), Some(b"LR".to_vec()));
        assert!(stern_brocot(&Frac::new(3, 2)).is_none());
    }

    /// Farey oracle: every term reduced, in range, sorted,
    /// and |F_n| = 1 + Σφ(k) — counted via the engine's phi.
    #[test]
    fn farey_properties() {
        for n in [1u32, 2, 6, 10, 30] {
            let f = farey(n);
            // |F_n| = 1 + Σ_{k=1}^{n} φ(k)
            let primes = crate::sieve::Primes::new(n as usize);
            let want = 1 + (1..=u64::from(n)).map(|k| primes.phi(k)).sum::<u64>();
            assert_eq!(f.len() as u64, want, "n = {n}");
            for w in f.windows(2) {
                assert!(w[0].cmp_frac(&w[1]) == std::cmp::Ordering::Less);
                // Farey neighbor determinant: |a/b − c/d| = 1/(bd)
                let det = w[1].num * w[0].den - w[0].num * w[1].den;
                assert_eq!(det, 1);
            }
        }
    }

    /// floor_sum oracle: direct summation.
    #[test]
    fn floor_sum_oracle() {
        let mut rng = SplitMix64::new(0xFA21);
        for _ in 0..3000 {
            let n = u64::from(rng.below(60));
            let m = 1 + u64::from(rng.below(30));
            let a = u64::from(rng.below(80));
            let b = u64::from(rng.below(80));
            let want: u128 = (0..n).map(|i| u128::from((a * i + b) / m)).sum();
            assert_eq!(floor_sum(n, m, a, b), want);
        }
    }

    /// Stern–Brocot oracle: the path's mediant replay hits
    /// the target, and every Farey member in F_n is
    /// reachable.
    #[test]
    fn stern_brocot_replays() {
        for n in [2u32, 5, 8] {
            for f in farey(n) {
                if f.num == 0 || f.num == f.den {
                    continue; // endpoints have no mediant path
                }
                let Some(path) = stern_brocot(&f) else {
                    panic!("no path for {f:?}");
                };
                let (mut lo, mut hi) = (Frac::new(0, 1), Frac::new(1, 1));
                let mut hit;
                for &c in &path {
                    hit = Frac::new(lo.num + hi.num, lo.den + hi.den);
                    if c == b'L' {
                        hi = hit;
                    } else {
                        lo = hit;
                    }
                }
                hit = Frac::new(lo.num + hi.num, lo.den + hi.den);
                assert_eq!(hit, f);
            }
        }
    }
}
