//! iptables-save / ip6tables-save 出力形式の解析。
//!
//! `*<table>` セクション、`:<chain> <policy> [<pkts>:<bytes>]` チェーン宣言、
//! `-A <chain> <rule>` ルール、`-N <chain>` ユーザー定義チェーン、
//! `COMMIT` の形を持つ設定を検出し、テーブル・チェーン・ルール数を
//! 整数で返す。
//!
//! # Examples
//!
//! ```
//! use izanagi_kit::iptablessave;
//!
//! let text = br#"*filter
//! :INPUT DROP [0:0]
//! :FORWARD DROP [0:0]
//! :OUTPUT ACCEPT [0:0]
//! -A INPUT -i lo -j ACCEPT
//! -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
//! COMMIT
//! "#;
//!
//! assert!(iptablessave::detect(text));
//! let c = iptablessave::parse(text).unwrap();
//! assert_eq!(c.tables, 1);
//! assert_eq!(c.chain_decls, 3);
//! assert_eq!(c.rules, 2);
//! ```

/// iptables-save の既知テーブル名。
const KNOWN_TABLES: &[&str] = &["filter", "nat", "mangle", "raw", "security", "rawpriority"];

/// iptables-save の集計。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Counts {
    /// `*<table>` テーブルセクション数。
    pub tables: usize,
    /// 既知テーブル数。
    pub known_tables: usize,
    /// `:<chain> <policy> […]` チェーン宣言数。
    pub chain_decls: usize,
    /// `-N <chain>` ユーザー定義チェーン数。
    pub user_chains: usize,
    /// `-A <chain> …` ルール追加数。
    pub rules: usize,
    /// `-j`/`-g` ジャンプ・ゴート指定数。
    pub jumps: usize,
    /// `COMMIT` 行数。
    pub commits: usize,
    /// `-m <mod>` マッチモジュール指定数。
    pub match_modules: usize,
}

/// `b` が iptables-save 出力らしいかを返す。
pub fn detect(b: &[u8]) -> bool {
    let c = match parse(b) {
        Some(c) => c,
        None => return false,
    };
    (c.known_tables >= 1 && c.commits >= 1) || (c.chain_decls >= 2 && c.rules >= 1)
}

/// iptables-save を解析して `Counts` を返す。
#[must_use]
pub fn parse(b: &[u8]) -> Option<Counts> {
    let s = std::str::from_utf8(b).ok()?;
    let mut counts = Counts {
        tables: 0,
        known_tables: 0,
        chain_decls: 0,
        user_chains: 0,
        rules: 0,
        jumps: 0,
        commits: 0,
        match_modules: 0,
    };
    let mut saw_any = false;
    for raw in s.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(tbl) = line.strip_prefix('*') {
            counts.tables += 1;
            saw_any = true;
            if KNOWN_TABLES.contains(&tbl.trim()) {
                counts.known_tables += 1;
            }
            continue;
        }
        if let Some(rest) = line.strip_prefix(':') {
            // `:CHAIN POLICY [pkts:bytes]`
            let name = rest.split_whitespace().next().unwrap_or("");
            if !name.is_empty()
                && name
                    .bytes()
                    .all(|c| c.is_ascii_alphanumeric() || matches!(c, b'-' | b'_'))
            {
                counts.chain_decls += 1;
                saw_any = true;
            }
            continue;
        }
        if line == "COMMIT" {
            counts.commits += 1;
            saw_any = true;
            continue;
        }
        if let Some(rest) = line.strip_prefix("-A ") {
            counts.rules += 1;
            saw_any = true;
            let _ = rest;
        }
        if let Some(rest) = line.strip_prefix("-N ") {
            if !rest.trim().is_empty() {
                counts.user_chains += 1;
                saw_any = true;
            }
        }
        counts.jumps += line.matches(" -j ").count();
        counts.jumps += line.matches(" -g ").count();
        counts.match_modules += line.matches(" -m ").count();
    }
    if !saw_any {
        return None;
    }
    Some(counts)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &[u8] = br#"# Generated by iptables-save v1.8.9
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:ufw-user-input - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -j ufw-user-input
-A FORWARD -o docker0 -j DOCKER
-N LOGGING
COMMIT
# Completed
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.0.0.0/8 -j MASQUERADE
COMMIT
"#;

    #[test]
    fn detects_iptables_save() {
        assert!(detect(SAMPLE));
        let c = parse(SAMPLE).unwrap();
        assert_eq!(c.tables, 2);
        assert_eq!(c.known_tables, 2);
        assert_eq!(c.chain_decls, 6);
        assert_eq!(c.user_chains, 1);
        assert_eq!(c.rules, 6);
        assert_eq!(c.jumps, 6);
        assert_eq!(c.match_modules, 2);
        assert_eq!(c.commits, 2);
    }

    #[test]
    fn rejects_other_text() {
        assert!(!detect(b"hello world"));
        assert!(!detect(b"-A INPUT"));
    }
}
