//! Kickstart 自動インストール応答ファイル(`*.ks`)の認識と計数。
//!
//! Kickstart は列0始まりのコマンド行(`install`/`url`/`repo`/`lang`/
//! `keyboard`/`network`/`rootpw`/`user`/`group`/`timezone`/`bootloader`/
//! `zerombr`/`clearpart`/`part`/`autopart`/`reqpart`/`volgroup`/`logvol`/
//! `raid`/`btrfs`/`firewall`/`selinux`/`services`/`xconfig`/`skipx`/`text`/
//! `graphical`/`reboot`/`halt`/`poweroff`/`firstboot`/`auth`/`authselect`/
//! `sshpw`/`iscsi`/`fcoe`/`ignoredisk`/`eula`/`timesource`/`rhsm`/
//! `syspurpose`/`zipl`/`mount`/`snapshot`/`nvdimm`/`driverdisk`/`device`/
//! `dmraid`/`multipath`/`zfcp`/`cdrom`/`harddrive`/`nfs`/`liveimg`/
//! `ostreesetup`/`ostreecontainer`/`logging`/`realm`/`sshpubkey`)と
//! `%packages`/`%end`/`%pre`/`%post`/`%pre-install`/`%addon`/`%include`/
//! `%ksappend`/`%anaconda`/`%onerror`/`%traceback` セクション、
//! `--opt=value`/`--opt value` オプション、`#` コメントで構成される。
//! `%packages`〜`%end` 内はパッケージ指定(`@group`/`pkg`/`^env`/`-pkg`)。
//!
//! ```
//! let b = b"# generated by anaconda\nlang en_US.UTF-8\nkeyboard us\ntimezone UTC --utc\nrootpw --iscrypted $6$x\nbootloader --location=mbr\nclearpart --all --initlabel\npart / --fstype=xfs --size=1024 --grow\n%packages\n@core\nvim-enhanced\n-git\n%end\n%post --interpreter=/bin/bash\nsystemctl enable sshd\n%end\n";
//! assert!(izanagi_kit::kickstart::detect(b));
//! let c = izanagi_kit::kickstart::parse(b).unwrap();
//! assert_eq!(c.commands, 7); // lang/keyboard/timezone/rootpw/bootloader/clearpart/part
//! assert_eq!(c.options, 9); // コマンド行 8 + %post の --interpreter
//! assert_eq!(c.sections, 2); // %packages + %post(%end は含めない)
//! assert_eq!(c.packages, 3); // @core/vim-enhanced/-git
//! ```

/// [`parse`] が返す計数。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Counts {
    /// 列0コマンド行(`lang`/`part` 等)の個数。
    pub commands: usize,
    /// `%packages`〜`%end` 等セクションマーカの個数(`%xxx` 行、`%end` 除く)。
    pub sections: usize,
    /// `%packages` ブロック内のパッケージ指定行の個数。
    pub packages: usize,
    /// `--opt`/`--opt=value` オプショントークンの総数。
    pub options: usize,
    /// スクリプト行(`%pre`/`%post`/`%onerror`/`%traceback` ブロック内)の個数。
    pub script_lines: usize,
    /// `#` コメント行の個数。
    pub comments: usize,
}

const COMMANDS: &[&str] = &[
    "install",
    "cdrom",
    "harddrive",
    "nfs",
    "url",
    "liveimg",
    "ostreesetup",
    "ostreecontainer",
    "repo",
    "lang",
    "keyboard",
    "network",
    "rootpw",
    "user",
    "group",
    "timezone",
    "timesource",
    "bootloader",
    "zerombr",
    "clearpart",
    "part",
    "partition",
    "autopart",
    "reqpart",
    "volgroup",
    "logvol",
    "raid",
    "btrfs",
    "firewall",
    "selinux",
    "services",
    "xconfig",
    "skipx",
    "text",
    "graphical",
    "cmdline",
    "reboot",
    "halt",
    "poweroff",
    "shutdown",
    "eula",
    "firstboot",
    "auth",
    "authconfig",
    "authselect",
    "sshpw",
    "sshpubkey",
    "iscsi",
    "iscsiname",
    "fcoe",
    "zfcp",
    "ignoredisk",
    "device",
    "deviceprobe",
    "driverdisk",
    "dmraid",
    "multipath",
    "logging",
    "monitor",
    "mouse",
    "langsupport",
    "lilocheck",
    "interactive",
    "upgrade",
    "mediacheck",
    "method",
    "key",
    "skipdsisk",
    "vnc",
    "displaymode",
    "module",
    "zypper",
    "realm",
    "rhsm",
    "syspurpose",
    "zipl",
    "mount",
    "snapshot",
    "nvdimm",
    "rescue",
    "unsupported_hardware",
    "hmc",
    "bootproto",
    "vlan",
    "bond",
    "team",
    "bridge",
    "fcoe",
    "zfcp",
];

const SECTION_HEADS: &[&str] = &[
    "%packages",
    "%pre",
    "%post",
    "%pre-install",
    "%addon",
    "%anaconda",
    "%onerror",
    "%traceback",
    "%ksappend",
    "%include",
    "%end",
];

fn section_tag(s: &str) -> Option<&str> {
    SECTION_HEADS.iter().find(|h| s.starts_with(*h)).copied()
}
fn strip_bom(t: &str) -> &str {
    t.strip_prefix('\u{feff}').unwrap_or(t)
}

/// Kickstart らしさを返す。既知コマンド行 ≥2、または `%packages`。
#[must_use]
pub fn detect(b: &[u8]) -> bool {
    let Ok(t) = std::str::from_utf8(b) else {
        return false;
    };
    let t = strip_bom(t);
    let mut hits = 0usize;
    for l in t.lines() {
        let s = l.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        if s.starts_with("%packages") {
            return true;
        }
        let head = s.split_whitespace().next().unwrap_or("");
        if COMMANDS.contains(&head) {
            hits += 1;
        }
    }
    hits >= 2
}

/// ファイル全体を走査して [`Counts`] を返す。
#[must_use]
pub fn parse(b: &[u8]) -> Option<Counts> {
    let t = std::str::from_utf8(b).ok()?;
    let t = strip_bom(t);
    let mut c = Counts {
        commands: 0,
        sections: 0,
        packages: 0,
        options: 0,
        script_lines: 0,
        comments: 0,
    };
    // 0=コマンド部, 1=packages, 2=script(pre/post/onerror/traceback), 3=addon(無視)
    let mut state = 0u8;
    for l in t.lines() {
        let s = l.trim();
        if s.is_empty() {
            continue;
        }
        if s.starts_with('#') {
            c.comments += 1;
            continue;
        }
        if let Some(h) = section_tag(s) {
            match h {
                "%end" => state = 0,
                "%packages" => {
                    c.sections += 1;
                    state = 1;
                }
                "%pre" | "%post" | "%pre-install" | "%onerror" | "%traceback" => {
                    c.sections += 1;
                    state = 2;
                    for tok in s.split_whitespace() {
                        if tok.starts_with("--") {
                            c.options += 1;
                        }
                    }
                }
                _ => {
                    c.sections += 1;
                }
            }
            continue;
        }
        match state {
            1 => c.packages += 1,
            2 => c.script_lines += 1,
            _ => {
                let head = s.split_whitespace().next().unwrap_or("");
                if COMMANDS.contains(&head) {
                    c.commands += 1;
                    for tok in s.split_whitespace() {
                        if tok.starts_with("--") {
                            c.options += 1;
                        }
                    }
                } else {
                    // 継続・生テキスト行もオプション混入可(保守的に数えない)
                }
            }
        }
    }
    Some(c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects() {
        assert!(detect(b"lang en_US.UTF-8\nkeyboard us\ntimezone UTC\n"));
        assert!(detect(b"%packages\n@core\n%end\n"));
    }

    #[test]
    fn rejects() {
        assert!(!detect(b"foo bar\nbaz qux\n"));
        assert!(!detect(&[0xff]));
    }

    #[test]
    fn counts() {
        let b = b"lang en_US\npart / --fstype=xfs --size=1024\n%packages\n@core\nvim\n%end\n%post\necho hi\n%end\n";
        let c = parse(b).unwrap();
        assert_eq!(c.commands, 2);
        assert_eq!(c.sections, 2);
        assert_eq!(c.packages, 2);
        assert_eq!(c.options, 2);
        assert_eq!(c.script_lines, 1);
    }

    #[test]
    fn copy_eq() {
        let c = parse(b"lang en_US\n").unwrap();
        let d = c;
        assert_eq!(c, d);
    }

    #[test]
    fn utf8_bom_is_tolerated() {
        assert_eq!(strip_bom("\u{feff}x"), "x");
        assert_eq!(strip_bom("x"), "x");
    }
}
