//! Multi-floor dungeon stack.
//!
//! `MultiMap` wraps multiple `Dungeon` floors into a stack, tracking the
//! current floor and exit/entrance connections between floors.
//!
//! Each floor is a `Dungeon` generated by `mapgen::generate_dungeon`. Floors
//! are connected by `Connector` records — a position on floor A leads to a
//! position on floor B (stairs up/down, portals, ladders).
//!
//! `DetHash` folds the current floor index, every floor's full `Dungeon` state
//! in stack order, and all connectors in canonical ascending-floor order, so the
//! complete multi-map state participates in replay hashes.

use crate::{
    mapgen::Dungeon,
    world_hash::{DetHash, Fnv1a},
};

/// A directional connection between two floors.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Connector {
    /// Floor index the connector originates on.
    pub from_floor: u32,
    /// World position on `from_floor`.
    pub from_x: i32,
    pub from_y: i32,
    /// Floor index the connector leads to.
    pub to_floor: u32,
    /// World position on `to_floor`.
    pub to_x: i32,
    pub to_y: i32,
}

impl DetHash for Connector {
    fn det_hash(&self, hasher: &mut Fnv1a) {
        hasher.write_u32(self.from_floor);
        hasher.write_i32(self.from_x);
        hasher.write_i32(self.from_y);
        hasher.write_u32(self.to_floor);
        hasher.write_i32(self.to_x);
        hasher.write_i32(self.to_y);
    }
}

/// A stack of `Dungeon` floors with inter-floor connectors.
pub struct MultiMap {
    floors: Vec<Dungeon>,
    connectors: Vec<Connector>,
    current_floor: u32,
}

impl MultiMap {
    /// Create a multi-map from an ordered list of floors.
    /// `current_floor` is clamped to a valid index.
    pub fn new(floors: Vec<Dungeon>, current_floor: u32) -> Self {
        let cf = if floors.is_empty() {
            0
        } else {
            current_floor.min(floors.len() as u32 - 1)
        };
        MultiMap {
            floors,
            connectors: Vec::new(),
            current_floor: cf,
        }
    }

    /// Number of floors.
    pub fn floor_count(&self) -> usize {
        self.floors.len()
    }

    /// Currently active floor index.
    pub fn current_floor(&self) -> u32 {
        self.current_floor
    }

    /// Change the active floor. Clamped to valid range.
    pub fn set_floor(&mut self, floor: u32) {
        if !self.floors.is_empty() {
            self.current_floor = floor.min(self.floors.len() as u32 - 1);
        }
    }

    /// Borrow the `Dungeon` on `floor`, or `None` if out of range.
    pub fn floor(&self, floor: usize) -> Option<&Dungeon> {
        self.floors.get(floor)
    }

    /// Borrow the currently active `Dungeon`.
    pub fn current(&self) -> Option<&Dungeon> {
        self.floors.get(self.current_floor as usize)
    }

    /// Mutably borrow the currently active `Dungeon`.
    pub fn current_mut(&mut self) -> Option<&mut Dungeon> {
        self.floors.get_mut(self.current_floor as usize)
    }

    /// Add a connector between two floor positions.
    pub fn add_connector(&mut self, connector: Connector) {
        self.connectors.push(connector);
    }

    /// All connectors originating on `floor`.
    pub fn exits_from(&self, floor: u32) -> Vec<&Connector> {
        self.connectors
            .iter()
            .filter(|c| c.from_floor == floor)
            .collect()
    }

    /// The connector at position `(x, y)` on `floor`, if any.
    pub fn connector_at(&self, floor: u32, x: i32, y: i32) -> Option<&Connector> {
        self.connectors
            .iter()
            .find(|c| c.from_floor == floor && c.from_x == x && c.from_y == y)
    }

    /// Find the first connector on any floor that leads to `dest_floor`.
    /// Returns `None` if no such connector exists.
    /// Useful for "navigate up" patterns where the player needs to find a
    /// stair that returns to the previous level without knowing its position.
    pub fn find_connector_to(&self, dest_floor: u32) -> Option<&Connector> {
        self.connectors.iter().find(|c| c.to_floor == dest_floor)
    }

    /// Remove the connector(s) that originate at `(from_floor, from_x, from_y)`.
    ///
    /// Returns `true` if at least one connector was removed, `false` if none
    /// matched. The typical use case has at most one connector per position
    /// (a staircase or portal), so this removes exactly one entry.
    pub fn remove_connector(&mut self, from_floor: u32, from_x: i32, from_y: i32) -> bool {
        let before = self.connectors.len();
        self.connectors
            .retain(|c| !(c.from_floor == from_floor && c.from_x == from_x && c.from_y == from_y));
        self.connectors.len() < before
    }

    /// Advance to the next floor (deeper / higher floor index). Returns `true`
    /// when the move succeeded, `false` when already on the last floor.
    pub fn move_down(&mut self) -> bool {
        let next = self.current_floor + 1;
        if next >= self.floors.len() as u32 {
            return false;
        }
        self.current_floor = next;
        true
    }

    /// Return to the previous floor (shallower / lower floor index). Returns
    /// `true` when the move succeeded, `false` when already on floor 0.
    pub fn move_up(&mut self) -> bool {
        if self.current_floor == 0 {
            return false;
        }
        self.current_floor -= 1;
        true
    }

    /// All connectors that originate on `from_floor` and lead to `to_floor`.
    /// Returns an empty `Vec` when no such connectors exist.
    ///
    /// Useful for multi-staircase levels: enumerate every stairwell between
    /// two specific floors without filtering through all exits.
    pub fn connectors_between(&self, from_floor: u32, to_floor: u32) -> Vec<&Connector> {
        self.connectors
            .iter()
            .filter(|c| c.from_floor == from_floor && c.to_floor == to_floor)
            .collect()
    }

    /// Link two floors with a **bidirectional** pair of connectors: stairs at
    /// `(ax, ay)` on `floor_a` lead to `(bx, by)` on `floor_b`, and back.
    /// The down-stair (`floor_a → floor_b`) is added first, then the return
    /// stair — two `add_connector` calls in one, covering the standard
    /// staircase pattern without hand-writing both records.
    pub fn link_floors(&mut self, floor_a: u32, ax: i32, ay: i32, floor_b: u32, bx: i32, by: i32) {
        self.add_connector(Connector {
            from_floor: floor_a,
            from_x: ax,
            from_y: ay,
            to_floor: floor_b,
            to_x: bx,
            to_y: by,
        });
        self.add_connector(Connector {
            from_floor: floor_b,
            from_x: bx,
            from_y: by,
            to_floor: floor_a,
            to_x: ax,
            to_y: ay,
        });
    }

    /// Shortest connector route from `from_floor` to `to_floor`, as the list
    /// of connectors to traverse in order. Breadth-first search over the
    /// directed floor graph, expanding connectors in **insertion order** so
    /// equal-length routes resolve deterministically (first-added wins).
    ///
    /// Returns `Some(vec![])` when `from_floor == to_floor`, and `None` when
    /// either floor index is out of range or no connector route exists.
    /// Connectors that point at out-of-range floors are skipped.
    ///
    /// This answers "which stairs do I take to get from the surface to floor
    /// 5?" — run grid pathfinding (e.g. [`pathfinding::astar`](crate::pathfinding::astar))
    /// *within* each floor toward `(from_x, from_y)` of each returned connector.
    pub fn find_floor_path(&self, from_floor: u32, to_floor: u32) -> Option<Vec<&Connector>> {
        let n = self.floors.len();
        if from_floor as usize >= n || to_floor as usize >= n {
            return None;
        }
        if from_floor == to_floor {
            return Some(Vec::new());
        }
        // BFS. `arrived_via[f]` = index of the connector that first reached f.
        let mut arrived_via: Vec<Option<usize>> = vec![None; n];
        let mut visited = vec![false; n];
        visited[from_floor as usize] = true;
        let mut queue = std::collections::VecDeque::new();
        queue.push_back(from_floor);
        while let Some(f) = queue.pop_front() {
            for (i, c) in self.connectors.iter().enumerate() {
                if c.from_floor != f || c.to_floor as usize >= n || visited[c.to_floor as usize] {
                    continue;
                }
                visited[c.to_floor as usize] = true;
                arrived_via[c.to_floor as usize] = Some(i);
                if c.to_floor == to_floor {
                    // Walk the arrival chain back to the start.
                    let mut path = Vec::new();
                    let mut cur = to_floor;
                    while cur != from_floor {
                        let ci = arrived_via[cur as usize]
                            .expect("every visited floor has an arrival connector");
                        path.push(&self.connectors[ci]);
                        cur = self.connectors[ci].from_floor;
                    }
                    path.reverse();
                    return Some(path);
                }
                queue.push_back(c.to_floor);
            }
        }
        None
    }

    /// Number of connectors on the shortest route from `from_floor` to
    /// `to_floor` (`Some(0)` when equal), or `None` when unreachable or out of
    /// range. Shorthand for `find_floor_path(..).map(|p| p.len() as u32)`.
    pub fn floor_distance(&self, from_floor: u32, to_floor: u32) -> Option<u32> {
        self.find_floor_path(from_floor, to_floor)
            .map(|p| p.len() as u32)
    }

    /// `true` when a connector route exists from `from_floor` to `to_floor`
    /// (always `true` for `from_floor == to_floor` in range).
    pub fn is_floor_reachable(&self, from_floor: u32, to_floor: u32) -> bool {
        self.find_floor_path(from_floor, to_floor).is_some()
    }
}

impl DetHash for MultiMap {
    fn det_hash(&self, hasher: &mut Fnv1a) {
        hasher.write_u32(self.current_floor);
        // Floors are mutable simulation state (`current_mut` hands out `&mut
        // Dungeon`). Fold them in stack order or two stacks with different
        // layouts but matching connectors+current_floor would collide.
        hasher.write_u32(self.floors.len() as u32);
        for floor in &self.floors {
            floor.det_hash(hasher);
        }
        hasher.write_u32(self.connectors.len() as u32);
        // Sort connectors by (from_floor, from_x, from_y) for canonical order.
        let mut sorted = self.connectors.clone();
        sorted.sort_by(|a, b| {
            a.from_floor
                .cmp(&b.from_floor)
                .then(a.from_x.cmp(&b.from_x))
                .then(a.from_y.cmp(&b.from_y))
        });
        for c in &sorted {
            c.det_hash(hasher);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        mapgen::{generate_dungeon, GenParams},
        rng::SplitMix64,
        world_hash::hash_state,
    };

    fn make_floor(seed: u64) -> Dungeon {
        let mut rng = SplitMix64::new(seed);
        generate_dungeon(
            40,
            20,
            &mut rng,
            GenParams {
                max_rooms: 5,
                min_room: 4,
                max_room: 8,
            },
        )
    }

    #[test]
    fn test_floor_count() {
        let floors = vec![make_floor(1), make_floor(2)];
        let m = MultiMap::new(floors, 0);
        assert_eq!(m.floor_count(), 2);
    }

    #[test]
    fn test_current_floor_clamped() {
        let floors = vec![make_floor(1), make_floor(2)];
        let m = MultiMap::new(floors, 99);
        assert_eq!(m.current_floor(), 1); // clamped to last valid
    }

    #[test]
    fn test_set_floor() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.set_floor(2);
        assert_eq!(m.current_floor(), 2);
    }

    #[test]
    fn test_current_returns_active_floor() {
        let floors = vec![make_floor(10)];
        let m = MultiMap::new(floors, 0);
        assert!(m.current().is_some());
    }

    #[test]
    fn test_add_and_query_connector() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 5,
            from_y: 5,
            to_floor: 1,
            to_x: 3,
            to_y: 3,
        });
        let exits = m.exits_from(0);
        assert_eq!(exits.len(), 1);
        assert_eq!(exits[0].to_floor, 1);
    }

    #[test]
    fn test_connector_at() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 7,
            from_y: 4,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        assert!(m.connector_at(0, 7, 4).is_some());
        assert!(m.connector_at(0, 0, 0).is_none());
        assert!(m.connector_at(1, 7, 4).is_none()); // wrong floor
    }

    #[test]
    fn test_empty_multimap() {
        let m = MultiMap::new(vec![], 0);
        assert_eq!(m.floor_count(), 0);
        assert!(m.current().is_none());
    }

    #[test]
    fn test_det_hash_same_state_same_hash() {
        let f1 = make_floor(42);
        let f2 = make_floor(42);
        let mut a = MultiMap::new(vec![f1], 0);
        let mut b = MultiMap::new(vec![f2], 0);
        let conn = Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        };
        a.add_connector(conn.clone());
        b.add_connector(conn);
        assert_eq!(hash_state(&a), hash_state(&b));
    }

    #[test]
    fn test_current_mut_returns_active_floor() {
        let floors = vec![make_floor(10)];
        let mut m = MultiMap::new(floors, 0);
        assert!(m.current_mut().is_some());
    }

    #[test]
    fn test_det_hash_differs_on_floor_change() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut a = MultiMap::new(floors.clone(), 0);
        let b = MultiMap::new(floors, 0);
        a.set_floor(1);
        assert_ne!(hash_state(&a), hash_state(&b));
    }

    #[test]
    fn test_det_hash_differs_on_floor_layout() {
        // Two stacks with identical current_floor (0) and no connectors but
        // DIFFERENT floor layouts must hash differently. Before the fix, the
        // `floors` Vec was omitted from det_hash, so these collided.
        let a = MultiMap::new(vec![make_floor(1)], 0);
        let b = MultiMap::new(vec![make_floor(2)], 0);
        assert_ne!(
            hash_state(&a),
            hash_state(&b),
            "different floor layouts must produce different hashes"
        );
    }

    #[test]
    fn test_det_hash_differs_on_floor_mutation() {
        // Mutating a floor through current_mut() must change the stack hash.
        let mut m = MultiMap::new(vec![make_floor(5)], 0);
        let before = hash_state(&m);
        // Push a room onto the active floor's registry (observable state).
        m.current_mut().unwrap().rooms.push(crate::mapgen::Rect {
            x: 0,
            y: 0,
            w: 1,
            h: 1,
        });
        let after = hash_state(&m);
        assert_ne!(before, after, "floor mutation must change the stack hash");
    }

    #[test]
    fn test_det_hash_identical_layouts_agree() {
        // Same seed → identical floors → identical hash (sanity that the new
        // floor fold is deterministic, not just discriminating).
        let a = MultiMap::new(vec![make_floor(7), make_floor(8)], 1);
        let b = MultiMap::new(vec![make_floor(7), make_floor(8)], 1);
        assert_eq!(hash_state(&a), hash_state(&b));
    }

    #[test]
    fn test_find_connector_to_finds_matching() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 3,
            from_y: 3,
            to_floor: 1,
            to_x: 5,
            to_y: 5,
        });
        m.add_connector(Connector {
            from_floor: 1,
            from_x: 7,
            from_y: 2,
            to_floor: 2,
            to_x: 4,
            to_y: 4,
        });
        let c = m.find_connector_to(2).unwrap();
        assert_eq!(c.to_floor, 2);
        assert_eq!(c.from_floor, 1);
    }

    #[test]
    fn test_find_connector_to_none_when_absent() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        assert!(m.find_connector_to(99).is_none());
    }

    #[test]
    fn test_find_connector_to_empty_map_returns_none() {
        let m = MultiMap::new(vec![], 0);
        assert!(m.find_connector_to(0).is_none());
    }

    #[test]
    fn test_connectors_between_finds_matching() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 1,
            from_x: 5,
            from_y: 5,
            to_floor: 2,
            to_x: 3,
            to_y: 3,
        });
        let between = m.connectors_between(0, 1);
        assert_eq!(between.len(), 1);
        assert_eq!(between[0].from_floor, 0);
        assert_eq!(between[0].to_floor, 1);
    }

    #[test]
    fn test_connectors_between_returns_empty_when_none() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        let between = m.connectors_between(1, 0); // reverse direction — none
        assert!(between.is_empty());
    }

    #[test]
    fn test_remove_connector_returns_true_when_found() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 3,
            from_y: 4,
            to_floor: 1,
            to_x: 1,
            to_y: 1,
        });
        assert!(m.remove_connector(0, 3, 4));
        assert!(m.exits_from(0).is_empty());
    }

    #[test]
    fn test_remove_connector_returns_false_when_absent() {
        let floors = vec![make_floor(1)];
        let mut m = MultiMap::new(floors, 0);
        assert!(!m.remove_connector(0, 5, 5));
    }

    #[test]
    fn test_remove_connector_leaves_other_connectors() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 5,
            from_y: 5,
            to_floor: 1,
            to_x: 6,
            to_y: 6,
        });
        m.remove_connector(0, 1, 1);
        let exits = m.exits_from(0);
        assert_eq!(exits.len(), 1);
        assert_eq!(exits[0].from_x, 5);
    }

    #[test]
    fn test_move_down_advances_floor() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        assert!(m.move_down());
        assert_eq!(m.current_floor(), 1);
    }

    #[test]
    fn test_move_down_at_last_floor_returns_false() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 1);
        assert!(!m.move_down());
        assert_eq!(m.current_floor(), 1);
    }

    #[test]
    fn test_move_up_decrements_floor() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 2);
        assert!(m.move_up());
        assert_eq!(m.current_floor(), 1);
    }

    #[test]
    fn test_move_up_at_floor_zero_returns_false() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        assert!(!m.move_up());
        assert_eq!(m.current_floor(), 0);
    }

    #[test]
    fn test_move_down_then_up_returns_to_original() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 1);
        assert!(m.move_down());
        assert!(m.move_up());
        assert_eq!(m.current_floor(), 1);
    }

    #[test]
    fn test_move_up_on_single_floor_returns_false() {
        let floors = vec![make_floor(1)];
        let mut m = MultiMap::new(floors, 0);
        assert!(!m.move_up());
        assert!(!m.move_down());
        assert_eq!(m.current_floor(), 0);
    }

    #[test]
    fn test_connectors_between_returns_multiple() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 3,
            from_y: 3,
            to_floor: 1,
            to_x: 4,
            to_y: 4,
        });
        let between = m.connectors_between(0, 1);
        assert_eq!(between.len(), 2);
    }

    // --- link_floors ---

    #[test]
    fn test_link_floors_creates_both_directions() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.link_floors(0, 5, 5, 1, 3, 3);
        let down = m.connector_at(0, 5, 5).expect("down stair");
        assert_eq!((down.to_floor, down.to_x, down.to_y), (1, 3, 3));
        let up = m.connector_at(1, 3, 3).expect("return stair");
        assert_eq!((up.to_floor, up.to_x, up.to_y), (0, 5, 5));
    }

    #[test]
    fn test_link_floors_round_trip_path() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.link_floors(0, 5, 5, 1, 3, 3);
        assert_eq!(m.floor_distance(0, 1), Some(1));
        assert_eq!(m.floor_distance(1, 0), Some(1), "return route exists");
    }

    #[test]
    fn test_link_floors_adds_exactly_two_connectors() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.link_floors(0, 1, 1, 1, 2, 2);
        assert_eq!(m.exits_from(0).len(), 1);
        assert_eq!(m.exits_from(1).len(), 1);
    }

    // --- find_floor_path ---

    /// Floors 0→1→2 chained with single connectors.
    fn chained_map() -> MultiMap {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 1,
            from_x: 5,
            from_y: 5,
            to_floor: 2,
            to_x: 6,
            to_y: 6,
        });
        m
    }

    #[test]
    fn test_find_floor_path_chain_in_order() {
        let m = chained_map();
        let path = m.find_floor_path(0, 2).expect("0→1→2 route");
        assert_eq!(path.len(), 2);
        assert_eq!((path[0].from_floor, path[0].to_floor), (0, 1));
        assert_eq!((path[1].from_floor, path[1].to_floor), (1, 2));
    }

    #[test]
    fn test_find_floor_path_same_floor_is_empty() {
        let m = chained_map();
        assert_eq!(m.find_floor_path(1, 1), Some(Vec::new()));
        assert_eq!(m.floor_distance(1, 1), Some(0));
    }

    #[test]
    fn test_find_floor_path_unreachable_returns_none() {
        // Connectors only go down; 2 → 0 has no route.
        let m = chained_map();
        assert!(m.find_floor_path(2, 0).is_none());
        assert!(!m.is_floor_reachable(2, 0));
    }

    #[test]
    fn test_find_floor_path_out_of_range_returns_none() {
        let m = chained_map();
        assert!(m.find_floor_path(0, 99).is_none());
        assert!(m.find_floor_path(99, 0).is_none());
    }

    #[test]
    fn test_find_floor_path_prefers_shortest() {
        // Both 0→1→2 and a direct 0→2 exist; BFS must take the direct hop.
        let mut m = chained_map();
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 9,
            from_y: 9,
            to_floor: 2,
            to_x: 1,
            to_y: 1,
        });
        let path = m.find_floor_path(0, 2).expect("direct route");
        assert_eq!(path.len(), 1);
        assert_eq!((path[0].from_x, path[0].from_y), (9, 9));
        assert_eq!(m.floor_distance(0, 2), Some(1));
    }

    #[test]
    fn test_find_floor_path_equal_routes_first_added_wins() {
        // Two direct 0→1 connectors: insertion order breaks the tie.
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 7,
            from_y: 7,
            to_floor: 1,
            to_x: 8,
            to_y: 8,
        });
        let path = m.find_floor_path(0, 1).unwrap();
        assert_eq!(path.len(), 1);
        assert_eq!((path[0].from_x, path[0].from_y), (1, 1), "first-added wins");
    }

    #[test]
    fn test_find_floor_path_skips_dangling_connectors() {
        // A connector to a floor index beyond the stack must not panic or
        // be traversed.
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 9, // dangling
            to_x: 0,
            to_y: 0,
        });
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 2,
            from_y: 2,
            to_floor: 1,
            to_x: 3,
            to_y: 3,
        });
        let path = m
            .find_floor_path(0, 1)
            .expect("valid route via second connector");
        assert_eq!(path.len(), 1);
        assert_eq!(path[0].to_floor, 1);
    }
}
