//! Multi-floor dungeon stack.
//!
//! `MultiMap` wraps multiple `Dungeon` floors into a stack, tracking the
//! current floor and exit/entrance connections between floors.
//!
//! Each floor is a `Dungeon` generated by `mapgen::generate_dungeon`. Floors
//! are connected by `Connector` records — a position on floor A leads to a
//! position on floor B (stairs up/down, portals, ladders).
//!
//! `DetHash` folds the current floor index plus all connectors in canonical
//! ascending-floor order so the multi-map state participates in replay hashes.
//! The individual `Dungeon` floors also implement `DetHash`, so a full snapshot
//! is possible via composition.

use crate::{
    mapgen::Dungeon,
    world_hash::{DetHash, Fnv1a},
};

/// A directional connection between two floors.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Connector {
    /// Floor index the connector originates on.
    pub from_floor: u32,
    /// World position on `from_floor`.
    pub from_x: i32,
    pub from_y: i32,
    /// Floor index the connector leads to.
    pub to_floor: u32,
    /// World position on `to_floor`.
    pub to_x: i32,
    pub to_y: i32,
}

impl DetHash for Connector {
    fn det_hash(&self, hasher: &mut Fnv1a) {
        hasher.write_u32(self.from_floor);
        hasher.write_i32(self.from_x);
        hasher.write_i32(self.from_y);
        hasher.write_u32(self.to_floor);
        hasher.write_i32(self.to_x);
        hasher.write_i32(self.to_y);
    }
}

/// A stack of `Dungeon` floors with inter-floor connectors.
pub struct MultiMap {
    floors: Vec<Dungeon>,
    connectors: Vec<Connector>,
    current_floor: u32,
}

impl MultiMap {
    /// Create a multi-map from an ordered list of floors.
    /// `current_floor` is clamped to a valid index.
    pub fn new(floors: Vec<Dungeon>, current_floor: u32) -> Self {
        let cf = if floors.is_empty() {
            0
        } else {
            current_floor.min(floors.len() as u32 - 1)
        };
        MultiMap {
            floors,
            connectors: Vec::new(),
            current_floor: cf,
        }
    }

    /// Number of floors.
    pub fn floor_count(&self) -> usize {
        self.floors.len()
    }

    /// Currently active floor index.
    pub fn current_floor(&self) -> u32 {
        self.current_floor
    }

    /// Change the active floor. Clamped to valid range.
    pub fn set_floor(&mut self, floor: u32) {
        if !self.floors.is_empty() {
            self.current_floor = floor.min(self.floors.len() as u32 - 1);
        }
    }

    /// Borrow the `Dungeon` on `floor`, or `None` if out of range.
    pub fn floor(&self, floor: usize) -> Option<&Dungeon> {
        self.floors.get(floor)
    }

    /// Borrow the currently active `Dungeon`.
    pub fn current(&self) -> Option<&Dungeon> {
        self.floors.get(self.current_floor as usize)
    }

    /// Mutably borrow the currently active `Dungeon`.
    pub fn current_mut(&mut self) -> Option<&mut Dungeon> {
        self.floors.get_mut(self.current_floor as usize)
    }

    /// Add a connector between two floor positions.
    pub fn add_connector(&mut self, connector: Connector) {
        self.connectors.push(connector);
    }

    /// All connectors originating on `floor`.
    pub fn exits_from(&self, floor: u32) -> Vec<&Connector> {
        self.connectors
            .iter()
            .filter(|c| c.from_floor == floor)
            .collect()
    }

    /// The connector at position `(x, y)` on `floor`, if any.
    pub fn connector_at(&self, floor: u32, x: i32, y: i32) -> Option<&Connector> {
        self.connectors
            .iter()
            .find(|c| c.from_floor == floor && c.from_x == x && c.from_y == y)
    }

    /// Find the first connector on any floor that leads to `dest_floor`.
    /// Returns `None` if no such connector exists.
    /// Useful for "navigate up" patterns where the player needs to find a
    /// stair that returns to the previous level without knowing its position.
    pub fn find_connector_to(&self, dest_floor: u32) -> Option<&Connector> {
        self.connectors.iter().find(|c| c.to_floor == dest_floor)
    }

    /// Remove the connector(s) that originate at `(from_floor, from_x, from_y)`.
    ///
    /// Returns `true` if at least one connector was removed, `false` if none
    /// matched. The typical use case has at most one connector per position
    /// (a staircase or portal), so this removes exactly one entry.
    pub fn remove_connector(&mut self, from_floor: u32, from_x: i32, from_y: i32) -> bool {
        let before = self.connectors.len();
        self.connectors
            .retain(|c| !(c.from_floor == from_floor && c.from_x == from_x && c.from_y == from_y));
        self.connectors.len() < before
    }

    /// All connectors that originate on `from_floor` and lead to `to_floor`.
    /// Returns an empty `Vec` when no such connectors exist.
    ///
    /// Useful for multi-staircase levels: enumerate every stairwell between
    /// two specific floors without filtering through all exits.
    pub fn connectors_between(&self, from_floor: u32, to_floor: u32) -> Vec<&Connector> {
        self.connectors
            .iter()
            .filter(|c| c.from_floor == from_floor && c.to_floor == to_floor)
            .collect()
    }
}

impl DetHash for MultiMap {
    fn det_hash(&self, hasher: &mut Fnv1a) {
        hasher.write_u32(self.current_floor);
        hasher.write_u32(self.connectors.len() as u32);
        // Sort connectors by (from_floor, from_x, from_y) for canonical order.
        let mut sorted = self.connectors.clone();
        sorted.sort_by(|a, b| {
            a.from_floor
                .cmp(&b.from_floor)
                .then(a.from_x.cmp(&b.from_x))
                .then(a.from_y.cmp(&b.from_y))
        });
        for c in &sorted {
            c.det_hash(hasher);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        mapgen::{generate_dungeon, GenParams},
        rng::SplitMix64,
        world_hash::hash_state,
    };

    fn make_floor(seed: u64) -> Dungeon {
        let mut rng = SplitMix64::new(seed);
        generate_dungeon(
            40,
            20,
            &mut rng,
            GenParams {
                max_rooms: 5,
                min_room: 4,
                max_room: 8,
            },
        )
    }

    #[test]
    fn test_floor_count() {
        let floors = vec![make_floor(1), make_floor(2)];
        let m = MultiMap::new(floors, 0);
        assert_eq!(m.floor_count(), 2);
    }

    #[test]
    fn test_current_floor_clamped() {
        let floors = vec![make_floor(1), make_floor(2)];
        let m = MultiMap::new(floors, 99);
        assert_eq!(m.current_floor(), 1); // clamped to last valid
    }

    #[test]
    fn test_set_floor() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.set_floor(2);
        assert_eq!(m.current_floor(), 2);
    }

    #[test]
    fn test_current_returns_active_floor() {
        let floors = vec![make_floor(10)];
        let m = MultiMap::new(floors, 0);
        assert!(m.current().is_some());
    }

    #[test]
    fn test_add_and_query_connector() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 5,
            from_y: 5,
            to_floor: 1,
            to_x: 3,
            to_y: 3,
        });
        let exits = m.exits_from(0);
        assert_eq!(exits.len(), 1);
        assert_eq!(exits[0].to_floor, 1);
    }

    #[test]
    fn test_connector_at() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 7,
            from_y: 4,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        assert!(m.connector_at(0, 7, 4).is_some());
        assert!(m.connector_at(0, 0, 0).is_none());
        assert!(m.connector_at(1, 7, 4).is_none()); // wrong floor
    }

    #[test]
    fn test_empty_multimap() {
        let m = MultiMap::new(vec![], 0);
        assert_eq!(m.floor_count(), 0);
        assert!(m.current().is_none());
    }

    #[test]
    fn test_det_hash_same_state_same_hash() {
        let f1 = make_floor(42);
        let f2 = make_floor(42);
        let mut a = MultiMap::new(vec![f1], 0);
        let mut b = MultiMap::new(vec![f2], 0);
        let conn = Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        };
        a.add_connector(conn.clone());
        b.add_connector(conn);
        assert_eq!(hash_state(&a), hash_state(&b));
    }

    #[test]
    fn test_current_mut_returns_active_floor() {
        let floors = vec![make_floor(10)];
        let mut m = MultiMap::new(floors, 0);
        assert!(m.current_mut().is_some());
    }

    #[test]
    fn test_det_hash_differs_on_floor_change() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut a = MultiMap::new(floors.clone(), 0);
        let b = MultiMap::new(floors, 0);
        a.set_floor(1);
        assert_ne!(hash_state(&a), hash_state(&b));
    }

    #[test]
    fn test_find_connector_to_finds_matching() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 3,
            from_y: 3,
            to_floor: 1,
            to_x: 5,
            to_y: 5,
        });
        m.add_connector(Connector {
            from_floor: 1,
            from_x: 7,
            from_y: 2,
            to_floor: 2,
            to_x: 4,
            to_y: 4,
        });
        let c = m.find_connector_to(2).unwrap();
        assert_eq!(c.to_floor, 2);
        assert_eq!(c.from_floor, 1);
    }

    #[test]
    fn test_find_connector_to_none_when_absent() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        assert!(m.find_connector_to(99).is_none());
    }

    #[test]
    fn test_find_connector_to_empty_map_returns_none() {
        let m = MultiMap::new(vec![], 0);
        assert!(m.find_connector_to(0).is_none());
    }

    #[test]
    fn test_connectors_between_finds_matching() {
        let floors = vec![make_floor(1), make_floor(2), make_floor(3)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 1,
            from_x: 5,
            from_y: 5,
            to_floor: 2,
            to_x: 3,
            to_y: 3,
        });
        let between = m.connectors_between(0, 1);
        assert_eq!(between.len(), 1);
        assert_eq!(between[0].from_floor, 0);
        assert_eq!(between[0].to_floor, 1);
    }

    #[test]
    fn test_connectors_between_returns_empty_when_none() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        let between = m.connectors_between(1, 0); // reverse direction — none
        assert!(between.is_empty());
    }

    #[test]
    fn test_remove_connector_returns_true_when_found() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 3,
            from_y: 4,
            to_floor: 1,
            to_x: 1,
            to_y: 1,
        });
        assert!(m.remove_connector(0, 3, 4));
        assert!(m.exits_from(0).is_empty());
    }

    #[test]
    fn test_remove_connector_returns_false_when_absent() {
        let floors = vec![make_floor(1)];
        let mut m = MultiMap::new(floors, 0);
        assert!(!m.remove_connector(0, 5, 5));
    }

    #[test]
    fn test_remove_connector_leaves_other_connectors() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 5,
            from_y: 5,
            to_floor: 1,
            to_x: 6,
            to_y: 6,
        });
        m.remove_connector(0, 1, 1);
        let exits = m.exits_from(0);
        assert_eq!(exits.len(), 1);
        assert_eq!(exits[0].from_x, 5);
    }

    #[test]
    fn test_connectors_between_returns_multiple() {
        let floors = vec![make_floor(1), make_floor(2)];
        let mut m = MultiMap::new(floors, 0);
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 1,
            from_y: 1,
            to_floor: 1,
            to_x: 2,
            to_y: 2,
        });
        m.add_connector(Connector {
            from_floor: 0,
            from_x: 3,
            from_y: 3,
            to_floor: 1,
            to_x: 4,
            to_y: 4,
        });
        let between = m.connectors_between(0, 1);
        assert_eq!(between.len(), 2);
    }
}
