//! OrcaSlicer 設定バンドル/プロファイル (`*.ini`) の検出・カウント。
//!
//! PrusaSlicer 派生だが `# generated by OrcaSlicer` ヘッダと、
//! `print_sequence`/`auto_calibrate`/`curr_bed_type`/`machine_pause_gcode`/
//! `preheat_time` 等の OrcaSlicer 固有キーを持つ。
//!
//! ```
//! let cfg = b"# generated by OrcaSlicer 2.0\n\n[printer]\nprinter_model = K1\n\
//!             nozzle_diameter = 0.4\nauto_calibrate = 0\ncurr_bed_type = Textured PEI Plate\n\
//!             machine_pause_gcode = M400 U1\n";
//! assert!(izanagi_kit::orcaslicer::detect(cfg));
//! let c = izanagi_kit::orcaslicer::parse(cfg).unwrap();
//! assert_eq!(c.entries, 5);
//! assert_eq!(c.orca_entries, 4);
//! assert_eq!(c.slicer_entries, 1);
//! ```

/// OrcaSlicer 固有 (PrusaSlicer に無い) キー。
const ORCA_KEYS: &[&str] = &[
    "print_sequence",
    "auto_calibrate",
    "curr_bed_type",
    "machine_pause_gcode",
    "preheat_time",
    "preheat_steps",
    "printer_model",
    "default_process_profile",
    "default_print_profile",
    "default_filament_profile",
    "default_project_filename",
    "filament_ids",
    "machine_usage",
    "nozzle_high_flow",
    "z_hop_type",
    "thumbnails",
    "thumbnails_with_bed_texture",
    "prime_volume",
    "single_extruder_multi_material_priming",
    "initial_layer_infill_speed",
    "first_layer_infill_speed",
    "wall_loops",
    "top_shell_layers",
    "bottom_shell_layers",
    "top_shell_thickness",
    "bottom_shell_thickness",
    "sparse_infill_density",
    "sparse_infill_pattern",
    "sparse_infill_anchor",
    "sparse_infill_anchor_max",
    "internal_solid_infill_speed",
    "internal_solid_infill_line_width",
    "top_surface_speed",
    "top_surface_line_width",
    "outer_wall_speed",
    "inner_wall_speed",
    "small_area_infill_flow_compensation",
    "enable_support",
    "support_type",
    "raft_layers",
    "skirt_loops",
    "brim_type",
    "brim_width",
    "tree_support_branch_diameter",
    "tree_support_wall_count",
    "exclude_object",
    "reduce_fan_slower",
    "overhang_fan_threshold",
    "overhang_speed_class",
    "detect_overhang_wall",
    "bridge_no_support",
    "max_bridge_length",
    "elefant_foot_compensation",
    "xy_contour_compensation",
    "xy_hole_compensation",
    "precise_wall",
    "seam_position",
    "staggered_inner_seam",
    "wall_direction",
    "ironing_type",
    "ironing_flow",
    "ironing_spacing",
    "ironing_speed",
    "ironing_inset",
    "printable_area",
    "printable_height",
    "extruder_clearance_height_to_lid",
    "extruder_clearance_height_to_rod",
    "extruder_clearance_radius",
    "nozzle_type",
    "nozzle_volume",
    "auxiliary_fan",
    "auxiliary_part_cooling_fan",
    "additional_cooling_fan_speed",
    "chamber_temperature",
    "chamber_temperatures",
    "filament_self",
    "filament_prime_speed",
    "filament_purge_speed",
    "filament_self_temperature",
];

/// PrusaSlicer と共通のスライサ系キー (存在確認用)。
const SLICER_KEYS: &[&str] = &[
    "layer_height",
    "first_layer_height",
    "nozzle_diameter",
    "printer_technology",
    "bed_temperature",
    "nozzle_temperature",
    "first_layer_temperature",
    "first_layer_bed_temperature",
    "filament_type",
    "filament_colour",
    "filament_color",
    "filament_vendor",
    "filament_diameter",
    "inherits",
    "start_gcode",
    "end_gcode",
    "before_layer_change_gcode",
    "layer_change_gcode",
    "machine_start_gcode",
    "machine_end_gcode",
    "wipe_tower",
    "retract_length",
    "retract_speed",
    "travel_speed",
    "silent_mode",
    "gcode_flavor",
    "bed_shape",
    "max_print_height",
    "compatible_printers_condition",
    "printer_variant",
    "printer_vendor",
];

/// セクション名の接頭辞。
const SECTION_HEADS: &[&str] = &[
    "print",
    "filament",
    "printer",
    "vendor",
    "presets",
    "sla_print",
    "sla_material",
];

fn key_of(s: &str) -> Option<(&str, &str)> {
    let i = s.find('=')?;
    let k = s[..i].trim();
    if k.is_empty() || !k.bytes().all(|c| c.is_ascii_alphanumeric() || c == b'_') {
        return None;
    }
    Some((k, s[i + 1..].trim()))
}

/// カウント結果。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Counts {
    /// `[print]`/`[filament]`/`[print:名前]` 等のセクション数。
    pub sections: usize,
    /// 既知キーの `key = value` 行数。
    pub entries: usize,
    /// OrcaSlicer 固有キーの行数。
    pub orca_entries: usize,
    /// PrusaSlicer 共有キーの行数。
    pub slicer_entries: usize,
    /// `*gcode` キーの行数。
    pub gcode_entries: usize,
    /// `generated by OrcaSlicer` ヘッダの有無 (0/1)。
    pub marker: usize,
    /// `#`/`;` コメント行数。
    pub comments: usize,
}

/// `b` が OrcaSlicer `*.ini` 形式かどうか。
#[must_use]
pub fn detect(b: &[u8]) -> bool {
    let Some(c) = parse(b) else {
        return false;
    };
    c.marker >= 1 || (c.orca_entries >= 2 && c.slicer_entries >= 1)
}

/// `b` を OrcaSlicer `*.ini` として解析し、行種別をカウントする。
#[must_use]
pub fn parse(b: &[u8]) -> Option<Counts> {
    let text = std::str::from_utf8(b).ok()?;
    let mut c = Counts {
        sections: 0,
        entries: 0,
        orca_entries: 0,
        slicer_entries: 0,
        gcode_entries: 0,
        marker: 0,
        comments: 0,
    };
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() {
            continue;
        }
        if s.starts_with('#') || s.starts_with(';') {
            c.comments += 1;
            if s.contains("OrcaSlicer") {
                c.marker = 1;
            }
            continue;
        }
        if s.starts_with('[') {
            let inner = s
                .strip_prefix('[')
                .unwrap_or(s)
                .split(']')
                .next()
                .unwrap_or("")
                .trim();
            let head = inner.split(':').next().unwrap_or("");
            if SECTION_HEADS.contains(&head) {
                c.sections += 1;
            }
            continue;
        }
        if let Some((k, _v)) = key_of(s) {
            let orca = ORCA_KEYS.contains(&k);
            let slicer = SLICER_KEYS.contains(&k);
            if !orca && !slicer {
                continue;
            }
            c.entries += 1;
            if orca {
                c.orca_entries += 1;
            } else {
                c.slicer_entries += 1;
            }
            if k.ends_with("gcode") {
                c.gcode_entries += 1;
            }
        }
    }
    if c.entries == 0 && c.marker == 0 {
        return None;
    }
    Some(c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_generated_header() {
        assert!(detect(b"# generated by OrcaSlicer 2.1.0\n\n[printer]\n"));
    }

    #[test]
    fn detects_orca_keys() {
        let cfg = b"[print:0.20 Standard]\nprint_sequence = by layer\nauto_calibrate = 1\n\
                    layer_height = 0.2\nmachine_pause_gcode = M400 U1\n";
        assert!(detect(cfg));
        let c = parse(cfg).unwrap();
        assert_eq!(c.orca_entries, 3);
        assert_eq!(c.slicer_entries, 1);
    }

    #[test]
    fn rejects_prusaslicer() {
        // PrusaSlicer のみのキー構成では OrcaSlicer と判定しない
        assert!(!detect(
            b"[printer]\nlayer_height = 0.2\nnozzle_diameter = 0.4\nbed_temperature = 60\n"
        ));
    }
}
