//! `poetry.lock` — `# This file is automatically @generated` +
//! `[[package]]` tables (`name`/`version`/`optional`/`python-versions`/
//! `files`/`[package.dependencies]`) + `[metadata]` (`lock-version`/`content-hash`).

use core::str::from_utf8;

#[derive(Debug, Clone)]
/// Parsed census of `poetry.lock`.
pub struct Poetry {
    /// `[metadata] lock-version`.
    pub lock_version: String,
    /// `[[package]]` entries.
    pub packages: usize,
    /// `name =` fields.
    pub names: usize,
    /// `version =` fields.
    pub versions: usize,
    /// `optional = true` entries.
    pub optional: usize,
    /// `python-versions =` constraints.
    pub python_versions: usize,
    /// `description =` fields.
    pub descriptions: usize,
    /// `files = [` table arrays.
    pub file_lists: usize,
    /// `groups = [` entries.
    pub groups: usize,
    /// `[package.dependencies]` tables.
    pub dependency_tables: usize,
    /// `markers`/`marker =` environment markers.
    pub markers: usize,
    /// `develop =` path dev entries.
    pub develop: usize,
    /// `[metadata] content-hash`.
    pub content_hash: usize,
    /// `[extras]`/`[package.extras]` tables.
    pub extras: usize,
    /// `#` comments.
    pub comments: usize,
}

/// `true` when the text looks like poetry.lock.
#[must_use]
pub fn detect(b: &[u8]) -> bool {
    let Ok(t) = from_utf8(b) else {
        return false;
    };
    t.contains("[[package]]") && (t.contains("python-versions") || t.contains("lock-version"))
}

impl Poetry {
    #[must_use]
    /// Parses `b` into `Poetry`.
    pub fn parse(b: &[u8]) -> Option<Self> {
        let t = from_utf8(b).ok()?;
        if !detect(b) {
            return None;
        }
        Some(Self {
            lock_version: t
                .lines()
                .find_map(|l| l.trim().strip_prefix("lock-version = "))
                .unwrap_or("")
                .trim_matches('"')
                .to_string(),
            packages: t.matches("[[package]]").count(),
            names: t.matches("name = ").count(),
            versions: t.matches("version = ").count(),
            optional: t.matches("optional = true").count(),
            python_versions: t.matches("python-versions").count(),
            descriptions: t.matches("description = ").count(),
            file_lists: t.matches("files = [").count(),
            groups: t.matches("groups = [").count(),
            dependency_tables: t.matches("[package.dependencies]").count(),
            markers: t.matches("markers").count() + t.matches("marker = ").count(),
            develop: t.matches("develop = ").count(),
            content_hash: t.matches("content-hash").count(),
            extras: t.matches("[extras]").count() + t.matches("[package.extras]").count(),
            comments: t
                .lines()
                .filter(|l| l.trim_start().starts_with('#'))
                .count(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIX: &[u8] = b"# This file is automatically @generated by Poetry\n\n[[package]]\nname = \"requests\"\nversion = \"2\x2e32\"\ndescription = \"HTTP\"\noptional = false\npython-versions = \">=3\x2e8\"\ngroups = [\"main\"]\nfiles = [\n    {file = \"requests.whl\"},\n]\n\n[package.dependencies]\nurllib3 = \"^3\"\n\n[metadata]\nlock-version = \"2\x2e1\"\npython-versions = \"^3\x2e12\"\ncontent-hash = \"abc\"\n";

    #[test]
    fn detects_poetry() {
        assert!(detect(FIX));
        assert!(!detect(b"[[package]]\nname = \"x\""));
    }

    #[test]
    fn parses_poetry() {
        let p = Poetry::parse(FIX).unwrap();
        assert_eq!(p.lock_version, "2\x2e1");
        assert_eq!(p.packages, 1);
        assert_eq!(p.names, 1);
        assert_eq!(p.python_versions, 2);
        assert_eq!(p.file_lists, 1);
        assert_eq!(p.groups, 1);
        assert_eq!(p.dependency_tables, 1);
        assert_eq!(p.content_hash, 1);
        assert!(Poetry::parse(b"").is_none());
    }
}
