//! PrusaSlicer 設定バンドル/プロファイル (`*.ini`) の検出・カウント。
//!
//! `# generated by PrusaSlicer …` ヘッダ、`[print]`/`[filament]`/`[printer]`/
//! `[vendor]`/`[presets]` および `[print:名前]` のような名付きプリセット、
//! `key = value` 形式のスライサ設定行で構成される。
//!
//! ```
//! let cfg = b"# generated by PrusaSlicer 2.6\n\n[printer]\nnozzle_diameter = 0.4\n\
//!             printer_technology = FFF\nstart_gcode = G28\n\n[filament]\n\
//!             filament_type = PLA\nnozzle_temperature = 215\n";
//! assert!(izanagi_kit::prusaslicer::detect(cfg));
//! let c = izanagi_kit::prusaslicer::parse(cfg).unwrap();
//! assert_eq!(c.sections, 2);
//! assert_eq!(c.entries, 5);
//! assert_eq!(c.gcode_entries, 1);
//! assert_eq!(c.temperature_entries, 1);
//! ```

use crate::textutil::strip_bom;
/// 既知の PrusaSlicer キー。
const KNOWN_KEYS: &[&str] = &[
    "layer_height",
    "first_layer_height",
    "perimeters",
    "spiral_vase",
    "top_solid_layers",
    "bottom_solid_layers",
    "top_solid_min_thickness",
    "bottom_solid_min_thickness",
    "fill_density",
    "fill_pattern",
    "fill_angle",
    "infill_every_layers",
    "infill_anchor",
    "infill_anchor_max",
    "perimeter_speed",
    "small_perimeter_speed",
    "external_perimeter_speed",
    "infill_speed",
    "solid_infill_speed",
    "top_solid_infill_speed",
    "support_material_speed",
    "bridge_speed",
    "gap_fill_enabled",
    "travel_speed",
    "travel_speed_z",
    "travel_acceleration",
    "first_layer_speed",
    "first_layer_speed_over_raft",
    "wipe",
    "retract_length",
    "retract_length_toolchange",
    "retract_restart_extra",
    "retract_restart_extra_toolchange",
    "retract_speed",
    "deretract_speed",
    "retract_lift",
    "retract_lift_above",
    "retract_lift_below",
    "retract_lift_top",
    "retract_layer_change",
    "retract_min_travel",
    "nozzle_temperature",
    "first_layer_temperature",
    "bed_temperature",
    "first_layer_bed_temperature",
    "chamber_temperature",
    "standby_temperature_delta",
    "filament_type",
    "filament_vendor",
    "filament_colour",
    "filament_color",
    "filament_diameter",
    "filament_spool_weight",
    "filament_cost",
    "filament_density",
    "filament_notes",
    "filament_max_volumetric_speed",
    "filament_settings_id",
    "print_settings_id",
    "printer_settings_id",
    "compatible_printers_condition",
    "compatible_prints_condition",
    "printer_technology",
    "printer_model",
    "printer_variant",
    "printer_vendor",
    "printer_notes",
    "inherits",
    "start_gcode",
    "end_gcode",
    "before_layer_change_gcode",
    "layer_change_gcode",
    "between_objects_gcode",
    "color_change_gcode",
    "pause_print_gcode",
    "toolchange_gcode",
    "machine_limits_usage",
    "machine_max_acceleration_e",
    "machine_max_acceleration_extruding",
    "machine_max_acceleration_retracting",
    "machine_max_acceleration_travel",
    "machine_max_acceleration_x",
    "machine_max_acceleration_y",
    "machine_max_acceleration_z",
    "machine_max_feedrate_e",
    "machine_max_feedrate_x",
    "machine_max_feedrate_y",
    "machine_max_feedrate_z",
    "machine_max_jerk_e",
    "machine_max_jerk_x",
    "machine_max_jerk_y",
    "machine_max_jerk_z",
    "machine_min_extruding_rate",
    "machine_min_travel_rate",
    "machine_max_junction_deviation",
    "nozzle_diameter",
    "nozzle_high_flow",
    "min_layer_height",
    "max_layer_height",
    "extruder_colour",
    "extruder_offset",
    "extruder_clearance_height",
    "extruder_clearance_radius",
    "gcode_comments",
    "gcode_label_objects",
    "gcode_resolution",
    "gcode_flavor",
    "silent_mode",
    "remaining_times",
    "bed_shape",
    "max_print_height",
    "use_relative_e_distances",
    "use_firmware_retraction",
    "use_volumetric_e",
    "wipe_tower",
    "wipe_tower_x",
    "wipe_tower_y",
    "wipe_tower_width",
    "wipe_tower_rotation_angle",
    "wipe_tower_brim_width",
    "idle_temperature",
    "single_extruder_multi_material",
    "cooling",
    "min_fan_speed",
    "max_fan_speed",
    "full_fan_speed_layer",
    "disable_fan_first_layers",
    "fan_below_layer_time",
    "slowdown_below_layer_time",
    "min_print_speed",
    "bridge_fan_speed",
    "support_material",
    "support_material_auto",
    "support_material_threshold",
    "support_material_with_sheath",
    "support_material_spacing",
    "support_material_pattern",
    "support_material_style",
    "support_material_interface_layers",
    "support_material_interface_spacing",
    "support_material_interface_speed",
    "support_material_bottom_layers",
    "support_material_xy_spacing",
    "support_material_bottom_distance",
    "support_material_closing_radius",
    "raft_layers",
    "raft_expansion",
    "raft_contact_distance",
    "raft_first_layer_density",
    "brim_type",
    "brim_separation",
    "brim_width",
    "skirt_height",
    "skirts",
    "min_skirt_length",
    "xy_size_compensation",
    "resolution",
    "elefant_foot_compensation",
    "thumbnails",
    "thumbnails_format",
    "post_process",
    "output_filename_format",
    "host_type",
    "printhost_host",
    "printhost_port",
    "printhost_apikey",
    "interface_shells",
    "mmu_segmented_region_max_width",
    "default_print_profile",
    "default_filament_profile",
    "default_sla_print_profile",
    "default_sla_material_profile",
];

/// セクション名の接頭辞として知られるもの (`[print:0.15 QUALITY]` 等)。
const SECTION_HEADS: &[&str] = &[
    "print",
    "filament",
    "printer",
    "vendor",
    "presets",
    "sla_print",
    "sla_material",
];

fn key_of(s: &str) -> Option<(&str, &str)> {
    let i = s.find('=')?;
    let k = s[..i].trim();
    if k.is_empty() || !k.bytes().all(|c| c.is_ascii_alphanumeric() || c == b'_') {
        return None;
    }
    Some((k, s[i + 1..].trim()))
}

/// カウント結果。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Counts {
    /// `[print]`/`[filament]`/`[print:名前]` 等のセクション数。
    pub sections: usize,
    /// `key = value` 行数。
    pub entries: usize,
    /// 既知キーによる行数。
    pub known_entries: usize,
    /// `*_gcode`/`start_gcode` 等の G-code 埋め込み行数。
    pub gcode_entries: usize,
    /// `*temperature*` キーの行数。
    pub temperature_entries: usize,
    /// `inherits` 継承指定の行数。
    pub inherits_entries: usize,
    /// `#`/`;` コメント行数 (generated ヘッダ含む)。
    pub comments: usize,
}

/// `b` が PrusaSlicer `*.ini` 形式かどうか。
#[must_use]
pub fn detect(b: &[u8]) -> bool {
    let text = match std::str::from_utf8(b) {
        Ok(t) => t,
        Err(_) => return false,
    };
    let text = strip_bom(text);
    // ジェネレータ署名は `#` コメント行にあるときだけ使う
    // — `key = value` の値中に同じ文字列があっても検出しない。
    if text
        .lines()
        .any(|l| l.trim_start().starts_with('#') && l.contains("generated by PrusaSlicer"))
    {
        return true;
    }
    let Some(c) = parse(b) else {
        return false;
    };
    c.entries >= 3 && c.known_entries >= 3
}

/// `b` を PrusaSlicer `*.ini` として解析し、行種別をカウントする。
#[must_use]
pub fn parse(b: &[u8]) -> Option<Counts> {
    let text = std::str::from_utf8(b).ok()?;
    let text = strip_bom(text);
    let mut c = Counts {
        sections: 0,
        entries: 0,
        known_entries: 0,
        gcode_entries: 0,
        temperature_entries: 0,
        inherits_entries: 0,
        comments: 0,
    };
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() {
            continue;
        }
        if s.starts_with('#') || s.starts_with(';') {
            c.comments += 1;
            continue;
        }
        if s.starts_with('[') {
            let inner = s
                .strip_prefix('[')
                .unwrap_or(s)
                .split(']')
                .next()
                .unwrap_or("")
                .trim();
            let head = inner.split(':').next().unwrap_or("");
            if SECTION_HEADS.contains(&head) {
                c.sections += 1;
            }
            continue;
        }
        if let Some((k, v)) = key_of(s) {
            if !KNOWN_KEYS.contains(&k) {
                continue;
            }
            c.entries += 1;
            c.known_entries += 1;
            if k.ends_with("gcode") || k == "start_gcode" || k == "end_gcode" {
                c.gcode_entries += 1;
            }
            if k.contains("temperature") {
                c.temperature_entries += 1;
            }
            if k == "inherits" || v == "inherits" {
                c.inherits_entries += 1;
            }
        }
    }
    if c.entries == 0 && c.sections == 0 {
        return None;
    }
    Some(c)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_generated_header() {
        assert!(detect(
            b"# generated by PrusaSlicer 2.7.4 on 2024-01-01\n\n[printer]\n"
        ));
    }

    #[test]
    fn counts_entries() {
        let cfg = b"[print:0.20 QUALITY]\nlayer_height = 0.2\nperimeters = 3\n\
                    fill_density = 15%\n\n[filament:PLA]\nfilament_type = PLA\n\
                    bed_temperature = 60\ninherits = *COMMON*\n";
        assert!(detect(cfg));
        let c = parse(cfg).unwrap();
        assert_eq!(c.sections, 2);
        assert_eq!(c.entries, 6);
        assert_eq!(c.temperature_entries, 1);
        assert_eq!(c.inherits_entries, 1);
    }

    #[test]
    fn rejects_other_ini() {
        assert!(!detect(b"[section]\nfoo = bar\nbaz = quux\naaa = bbb\n"));
    }

    #[test]
    fn generator_marker_must_be_a_comment() {
        // The signature inside a value (not on a `#` line) must not trigger.
        assert!(!detect(
            b"[section]\nnote = generated by PrusaSlicer 2.6\nfoo = bar\nbaz = quux\n"
        ));
        assert!(detect(
            b"# generated by PrusaSlicer 2.6\n[print]\nfoo = bar\n"
        ));
    }

    #[test]
    fn utf8_bom_is_tolerated() {
        assert_eq!(strip_bom("\u{feff}x"), "x");
        assert_eq!(strip_bom("x"), "x");
    }
}
