//! Simple File Verify (`.sfv`) — `filename CRC32` lines.
//!
//! Each non-comment line is `<name> <8 hex digits>`; `;` starts a
//! comment (usually a header block produced by the generator). Names
//! may contain spaces — the CRC is the last whitespace-separated token.
//!
//! ```
//! use izanagi_kit::sfv::parse;
//!
//! let s = parse(b";generated by test\nfile one.bin DEADBEEF\nb.bin 00000000\n").unwrap();
//! assert_eq!(s.entries.len(), 2);
//! assert_eq!(s.entries[0].name, "file one.bin");
//! assert_eq!(s.entries[0].crc32, 0xDEADBEEF);
//! ```

/// One `name crc` line.
#[derive(Clone, Debug)]
pub struct SfvEntry {
    /// The filename (may contain spaces).
    pub name: String,
    /// Declared CRC-32.
    pub crc32: u32,
}

/// A parsed `.sfv` file.
#[derive(Clone, Debug)]
pub struct Sfv {
    /// Entries in file order.
    pub entries: Vec<SfvEntry>,
}

/// Parse an SFV listing. `None` on a malformed line, bad hex, or an
/// empty file.
pub fn parse(d: &[u8]) -> Option<Sfv> {
    let text = std::str::from_utf8(d).ok()?;
    let mut entries = Vec::new();
    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with(';') {
            continue;
        }
        let (name, crc) = t.rsplit_once(|c: char| c.is_whitespace())?;
        if name.trim().is_empty() {
            return None;
        }
        if crc.len() != 8 || !crc.bytes().all(|b| b.is_ascii_hexdigit()) {
            return None;
        }
        entries.push(SfvEntry {
            name: name.trim_end().to_string(),
            crc32: u32::from_str_radix(crc, 16).ok()?,
        });
    }
    if entries.is_empty() {
        return None;
    }
    Some(Sfv { entries })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses() {
        let s = parse(b"; comment\na b.iso CAFECAFE\nz 12345678\n").unwrap();
        assert_eq!(s.entries[0].name, "a b.iso");
        assert_eq!(s.entries[1].crc32, 0x12345678);
    }

    #[test]
    fn rejects() {
        assert!(parse(b"").is_none());
        assert!(parse(b";only comments\n").is_none());
        assert!(parse(b"nocrc\n").is_none());
        assert!(parse(b"f DEADBEE\n").is_none());
        assert!(parse(b"f ZZZZZZZZ\n").is_none());
    }
}
