//! Every `detect(&[u8]) -> bool` in the crate, exercised against malformed
//! input — plus a completeness check that `izanagi_kit::DETECTORS` lists all
//! of them.
//!
//! The census contract is "recognize, never reject with a crash": a detector
//! that panics on truncated or hostile bytes takes the whole sniff pass down
//! with it. Nothing in the per-module unit tests guards that class, so this
//! file feeds every registered detector a shared corpus of truncations,
//! marker lookalikes, single bytes, and deterministic noise. A panic in any
//! detector fails the test with the module name attached.
//!
//! The second test ties the registry to the source tree: any `*.rs` module
//! declaring `pub fn detect(` must appear in `DETECTORS`, so adding a census
//! module without registering it fails the build.

use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::fs;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::Path;

/// Marker-rich fodder: every shape the detectors look for, cut mid-token,
/// plus comment/string contexts that try to smuggle markers in.
const FODDER: &str = concat!(
    "{\"scenes\": [], \"settings\": {\"startSceneId\": \"1\"}, \"rules\": {\"x\": 1},",
    "\"name\": \"p\", \"status\": true, \"parameters\": {},",
    "\"dependencies\": {\"com.unity.ugui\": \"1.0.0\"}, \"project_type\": \"lua\",",
    "\"engine_version\": \"x\", \"driver\": \"docker\", \"cpus\": 2, \"filters\": {}}",
    "apiVersion: k0s.k0sproject.io/v1beta1\nkind: ClusterConfig\npipeline:\n",
    "  name: ci\nidentifier: x\nstages:\n  - stage:\n      name: b\n",
    "# generated by PrusaSlicer 2.6\n[printer]\nnozzle_diameter = 0.4\n",
    "%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n--- !u!129 &1\nPlayerSettings:\n",
    "function love.conf(t)\nend\nfunction love.update(dt)\nend\n",
    "box.cfg{listen = 3301}\n-- box.cfg{x}\n",
    "// \"rules\": {}\n# apiVersion: k0s.k0sproject.io\n",
    "key: value # comment\nplain text 漢字 🎮 \u{0}\u{ff}",
);

fn corpus() -> Vec<Vec<u8>> {
    let mut out: Vec<Vec<u8>> = vec![Vec::new()];
    for b in 0..=255u8 {
        out.push(vec![b]);
    }
    let fodder = FODDER.as_bytes();
    // Every prefix of the fodder, so markers get cut at every position.
    for n in 0..=fodder.len() {
        out.push(fodder[..n].to_vec());
    }
    // The fodder with each single byte corrupted, sparsely sampled.
    for i in (0..fodder.len()).step_by(7) {
        let mut m = fodder.to_vec();
        m[i] ^= 0xA5;
        out.push(m);
    }
    // Deterministic noise (SplitMix64 output bytes), several lengths.
    let mut s = 0x9E37_79B9_7F4A_7C15_u64;
    let mut next = || {
        s = s.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = s;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    };
    for len in [2usize, 5, 17, 64, 256, 1024] {
        for _ in 0..8 {
            let buf: Vec<u8> = (0..len).map(|_| (next() & 0xFF) as u8).collect();
            out.push(buf);
        }
    }
    // Homogeneous fills.
    for len in [8usize, 64, 512] {
        out.push(vec![0x00; len]);
        out.push(vec![0xFF; len]);
        out.push(vec![b'{'; len]);
        out.push(vec![b'#'; len]);
    }
    out
}

#[test]
fn no_detector_panics_on_malformed_input() {
    let corpus = corpus();
    for &(name, detect) in izanagi_kit::DETECTORS {
        for input in &corpus {
            let result = catch_unwind(AssertUnwindSafe(|| detect(input)));
            assert!(
                result.is_ok(),
                "{name}::detect panicked on {}-byte input {:02x?}…",
                input.len(),
                &input[..input.len().min(16)]
            );
        }
    }
}

#[test]
fn detectors_registry_covers_every_module_with_detect() {
    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut expected: BTreeSet<String> = BTreeSet::new();
    for entry in fs::read_dir(&src).unwrap() {
        let path = entry.unwrap().path();
        if path.extension() != Some(OsStr::new("rs"))
            || path.file_name() == Some(OsStr::new("lib.rs"))
        {
            continue;
        }
        if fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
            .contains("pub fn detect(")
        {
            expected.insert(path.file_stem().unwrap().to_str().unwrap().to_string());
        }
    }
    let registered: BTreeSet<String> = izanagi_kit::DETECTORS
        .iter()
        .map(|(n, _)| (*n).to_string())
        .collect();
    let missing: Vec<&String> = expected.difference(&registered).collect();
    assert!(
        missing.is_empty(),
        "modules with `pub fn detect(` missing from DETECTORS: {missing:?}"
    );
    let extra: Vec<&String> = registered.difference(&expected).collect();
    assert!(
        extra.is_empty(),
        "DETECTORS entries without a `pub fn detect(` module: {extra:?}"
    );
}
