//! Every free-function `pub fn parse(x: &[u8])` in the crate, exercised
//! against malformed input — plus a completeness check that
//! `izanagi_kit::PARSERS` lists all of them.
//!
//! Parsers run on untrusted bytes: truncation and corruption must produce
//! `None`/partial results, never a crash. The per-module unit tests only
//! cover the happy path, so this file feeds every registered parser the
//! same shared corpus as the detector sweep (truncations of marker-rich
//! text, single bytes, bit flips, deterministic noise). A panic in any
//! parser fails the test with the module name attached.
//!
//! The second test ties the registry to the source tree: any `*.rs` module
//! declaring a free `pub fn parse(x: &[u8])` must appear in `PARSERS`, so
//! adding a census module without registering it fails the build.

use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::fs;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::Path;

/// Marker-rich fodder: every shape the parsers look for, cut mid-token,
/// plus comment/string contexts that try to smuggle markers in.
const FODDER: &str = concat!(
    "{\"scenes\": [], \"settings\": {\"startSceneId\": \"1\"}, \"rules\": {\"x\": 1},",
    "\"name\": \"p\", \"status\": true, \"parameters\": {},",
    "\"dependencies\": {\"com.unity.ugui\": \"1.0.0\"}, \"project_type\": \"lua\",",
    "\"engine_version\": \"x\", \"driver\": \"docker\", \"cpus\": 2, \"filters\": {}}",
    "apiVersion: k0s.k0sproject.io/v1beta1\nkind: ClusterConfig\npipeline:\n",
    "  name: ci\nidentifier: x\nstages:\n  - stage:\n      name: b\n",
    "# generated by PrusaSlicer 2.6\n[printer]\nnozzle_diameter = 0.4\n",
    "%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n--- !u!129 &1\nPlayerSettings:\n",
    "function love.conf(t)\nend\nfunction love.update(dt)\nend\n",
    "box.cfg{listen = 3301}\n-- box.cfg{x}\n",
    "// \"rules\": {}\n# apiVersion: k0s.k0sproject.io\n",
    "key: value # comment\nplain text 漢字 🎮 \u{0}\u{ff}",
);

fn corpus() -> Vec<Vec<u8>> {
    let mut out: Vec<Vec<u8>> = vec![Vec::new()];
    for b in 0..=255u8 {
        out.push(vec![b]);
    }
    let fodder = FODDER.as_bytes();
    // Every prefix of the fodder, so markers get cut at every position.
    for n in 0..=fodder.len() {
        out.push(fodder[..n].to_vec());
    }
    // The fodder with each single byte corrupted, sparsely sampled.
    for i in (0..fodder.len()).step_by(7) {
        let mut m = fodder.to_vec();
        m[i] ^= 0xA5;
        out.push(m);
    }
    // Deterministic noise (SplitMix64 output bytes), several lengths.
    let mut s = 0x9E37_79B9_7F4A_7C15_u64;
    let mut next = || {
        s = s.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = s;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    };
    for len in [2usize, 5, 17, 64, 256, 1024] {
        for _ in 0..8 {
            let buf: Vec<u8> = (0..len).map(|_| (next() & 0xFF) as u8).collect();
            out.push(buf);
        }
    }
    // Homogeneous fills.
    for len in [8usize, 64, 512] {
        out.push(vec![0x00; len]);
        out.push(vec![0xFF; len]);
        out.push(vec![b'{'; len]);
        out.push(vec![b'#'; len]);
    }
    out
}

#[test]
fn no_parser_panics_on_malformed_input() {
    let corpus = corpus();
    for &(name, parse) in izanagi_kit::PARSERS {
        for input in &corpus {
            let result = catch_unwind(AssertUnwindSafe(|| parse(input)));
            assert!(
                result.is_ok(),
                "{name}::parse panicked on {}-byte input {:02x?}…",
                input.len(),
                &input[..input.len().min(16)]
            );
        }
    }
}

#[test]
fn parsers_registry_covers_every_module_with_parse() {
    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
    let mut expected: BTreeSet<String> = BTreeSet::new();
    for entry in fs::read_dir(&src).unwrap() {
        let path = entry.unwrap().path();
        if path.extension() != Some(OsStr::new("rs"))
            || path.file_name() == Some(OsStr::new("lib.rs"))
        {
            continue;
        }
        let text = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        // Free functions only: a `pub fn parse` at column 0 whose FIRST
        // parameter is `&[u8]`. Indented declarations are methods
        // (`impl T::parse`), and parses taking extra leading parameters
        // (`parse(cob_id: u16, data: &[u8])`, `parse(d: &[u8], at: usize)`)
        // are out of scope for the byte-corpus sweep.
        let has_byte_parse = text.lines().any(|l| {
            l.starts_with("pub fn parse(")
                && l.find(": &[u8])")
                    .is_some_and(|p| !l["pub fn parse(".len()..p].contains(','))
        });
        if has_byte_parse {
            expected.insert(path.file_stem().unwrap().to_str().unwrap().to_string());
        }
    }
    let registered: BTreeSet<String> = izanagi_kit::PARSERS
        .iter()
        .map(|(n, _)| (*n).to_string())
        .collect();
    let missing: Vec<&String> = expected.difference(&registered).collect();
    assert!(
        missing.is_empty(),
        "modules with a free `pub fn parse(_: &[u8])` missing from PARSERS: {missing:?}"
    );
    let extra: Vec<&String> = registered.difference(&expected).collect();
    assert!(
        extra.is_empty(),
        "PARSERS entries without a matching `pub fn parse(_: &[u8])` module: {extra:?}"
    );
}
